In [56]:
import pandas as pd
import numpy as np

In [57]:
data = pd.read_csv('../course_lead_scoring_2026.csv')

In [58]:
data.head()

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1

### **Подготовка данных.**

In [59]:
#кол-во пропущенных значений
data.isnull().sum()

lead_source                 148
industry                    240
employment_status           194
location                    208
annual_income               369
number_of_courses_viewed      0
interaction_count             0
lead_score                   35
converted                     0
dtype: int64

In [60]:
#тип данных каждого столбца
data.dtypes

lead_source                     str
industry                        str
employment_status               str
location                        str
annual_income               float64
number_of_courses_viewed      int64
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

In [61]:
cat_cols = data.select_dtypes(include=["object", "str"]).columns
num_cols = data.select_dtypes(include="number").columns

#заполним пропущенные значения
data[cat_cols] = data[cat_cols].fillna("NA")
data[num_cols] = data[num_cols].fillna(0.0)

In [62]:
data.isnull().sum().sum()

np.int64(0)

### **Задание 1.**
Найдем моду столбца industry.

In [63]:
data["industry"].value_counts()

industry
technology       1173
retail            925
healthcare        840
finance           720
education         639
manufacturing     463
NA                240
Name: count, dtype: int64

### **Задание 2.**
Корреляционная матрица.

In [64]:
#матрица корреляций
corr_matrix = data.corr(numeric_only=True)
corr_matrix

,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
annual_income,1.000000,0.161300,0.122842,0.229496,0.189652
number_of_courses_viewed,0.161300,1.000000,0.721609,0.757204,0.395038
interaction_count,0.122842,0.721609,1.000000,0.915746,0.448624
lead_score,0.229496,0.757204,0.915746,1.000000,0.483246
converted,0.189652,0.395038,0.448624,0.483246,1.000000

In [65]:
#пары, которые нас интересуют
pairs = [
    ("interaction_count", "lead_score"),
    ("number_of_courses_viewed", "lead_score"),
    ("number_of_courses_viewed", "interaction_count"),
    ("annual_income", "interaction_count")
]

results = [] #список словарей

#соберем нужные нам пары
for col1, col2 in pairs:
    corr = corr_matrix.loc[col1, col2]
    results.append({
        "Пара признаков": f"{col1} и {col2}",
        "Корреляция": corr
    })

#превратим это в таблицу
result_df = pd.DataFrame(results)
#отсортируем
result_df = result_df.sort_values(
    by="Корреляция", ascending=False
)

result_df

                                 Пара признаков  Корреляция
0                interaction_count и lead_score    0.915746
1         number_of_courses_viewed и lead_score    0.757204
2  number_of_courses_viewed и interaction_count    0.721609
3             annual_income и interaction_count    0.122842

### **Разделим данные.**

In [66]:
from sklearn.model_selection import train_test_split

df_full_train, df_test = train_test_split(data, test_size=0.2, random_state=42)

df_train, df_val = train_test_split(
    df_full_train, test_size=0.25, random_state=42
)

### **Задание 3.**
Mutual Information (MI) между признаками и таргетом.

**Mutual Information (MI)** — _показывает, насколько один признак помогает нам лучше понять другой. Она удобна для категориальных признаков, потому что умеет находить связь между разными категориями без необходимости превращать их в числа._

In [67]:
from sklearn.metrics import mutual_info_score

In [73]:
mi = {}

for col in cat_cols:
    mi[col] = round(mutual_info_score(df_train[col], df_train['converted']), 2)

mi_df = pd.DataFrame(mi.items(), columns=['feature', 'MI'])
mi_df.sort_values(by='MI', ascending=False)
mi_df

             feature    MI
0        lead_source  0.03
1           industry  0.00
2  employment_status  0.02
3           location  0.00

### **Задание 4.**
Обучим модель, которая будет предсказывать, зарегистрируется ли клиент на платформе (converted).

In [74]:
from sklearn.feature_extraction import DictVectorizer
#DictVectorizer автоматически применяет One-Hot Encoding к категориальным признакам и сохраняет числовые признаки в числовом виде.
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

_закодируем категориальные признаки в обучающих данных_

In [77]:
#отделим таргет
y_train = df_train['converted']
X_train = df_train.drop(columns=['converted'])

In [83]:
#создадим словарь из каждой строки
train_dict = X_train.to_dict(orient='records')

#преобразователь для кодирования
dv = DictVectorizer(sparse=False)
#изучим признаки и сразу преобразуем
X_train_encoded = dv.fit_transform(train_dict)

_закодируем категориальные признаки в валидационных данных_

In [81]:
#отделим таргет
y_val = df_val['converted']
X_val = df_val.drop(columns=['converted'])

In [84]:
#словарь из каждой строки
val_dict = X_val.to_dict(orient='records')

#преобразуем
X_val_encoded = dv.transform(val_dict)

_Обучим логистическую регрессию._

In [97]:
model = LogisticRegression(
    solver='liblinear',
    C=1.0,
    max_iter=1000,
    random_state=42
)
model.fit(X_train_encoded, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [98]:
#предсказание модели
y_pred = model.predict(X_val_encoded)

In [99]:
#доля правильных предсказаний модели
accuracy_score(y_val, y_pred)

0.645

### **Задание 5.**
Выясним, какой признак сильнее всего влияет на качество нашей логистической регрессии.

In [100]:
#сохраним исходную точность
original_accuracy = accuracy_score(y_val, y_pred)

0.645

In [101]:
#признаки для исключения
features_to_remove = [
    'lead_source',
    'number_of_courses_viewed',
    'interaction_count'
]

In [102]:
#будем смотреть на разные результаты
results = {}

for feature in features_to_remove:
    #удалим
    X_train_reduced = X_train.drop(columns=[feature])
    X_val_reduced = X_val.drop(columns=[feature])

    #для кодирования признаков
    dv_reduced = DictVectorizer(sparse=False)

    #кодируем признаки
    X_train_reduced_encoded = dv_reduced.fit_transform(
        X_train_reduced.to_dict(orient='records')
    )
    X_val_reduced_encoded = dv_reduced.transform(
        X_val_reduced.to_dict(orient='records')
    )

    #модель
    model = LogisticRegression(
        solver='liblinear',
        C=1.0,
        max_iter=1000,
        random_state=42
    )

    #обучаем модель
    model.fit(X_train_reduced_encoded, y_train)
    y_pred_reduced = model.predict(X_val_reduced_encoded)

    #считаем результаты
    accuracy = accuracy_score(y_val, y_pred_reduced)
    difference = original_accuracy - accuracy

    results[feature] = difference

results

{'lead_source': 0.0030000000000000027,
 'number_of_courses_viewed': 0.0020000000000000018,
 'interaction_count': 0.04400000000000004}

### **Задание 6.**
Исследуем, как параметр C влияет на качество логистической регрессии.

In [103]:
C_values = [0.000001, 0.00001, 0.0001, 0.001]

In [104]:
results = {}

for C in C_values:
    #модель
    model = LogisticRegression(
        solver='liblinear',
        C=C,
        max_iter=1000,
        random_state=42
    )

    #обучим
    model.fit(X_train_encoded, y_train)

    #предсказание
    y_pred = model.predict(X_val_encoded)

    #результат
    accuracy = accuracy_score(y_val, y_pred)
    results[C] = round(accuracy, 3)

for C, accuracy in results.items():
    print(f'C = {C}: accuracy = {accuracy:.3f}')

C = 1e-06: accuracy = 0.598
C = 1e-05: accuracy = 0.598
C = 0.0001: accuracy = 0.613
C = 0.001: accuracy = 0.645